spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: testuser
    password: testpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ??? ?? ??
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  session:
    store-type: redis
    redis:
      namespace: shboard:session
      timeout: 1800
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: my-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer